### ISSUE TITLE
Compatibility issue with net 8.0

### ISSUE THREAD

**Issue by helvertti** [FrendsPlatform/Frends.Regex#23]
When importing process from net 6.0 to net 8.0, the process validaiton ends with an error:

"Process compilation failed

Frends.ExecutableProcess.frends_UTIL_Trans.cs(296,62): error CS0234: The type or namespace name 'ReplaceResult' does not exist in the namespace 'Frends.Regex' (are you missing an assembly reference?)

Frends.ExecutableProcess.frends_UTIL_Trans.cs(297,62): error CS0234: The type or namespace name 'ReplaceResult' does not exist in the namespace 'Frends.Regex' (are you missing an assembly reference?)

Frends.ExecutableProcess.frends_UTIL_Trans.cs(298,62): error CS0234: The type or namespace name 'ReplaceResult' does not exist in the namespace 'Frends.Regex' (are you missing an assembly reference?)

Frends.ExecutableProcess.frends_UTIL_Trans.cs(299,62): error CS0234: The type or namespace name 'ReplaceResult' does not exist in the namespace 'Frends.Regex' (are you missing an assembly reference?)

Frends.ExecutableProcess.frends_UTIL_Trans.cs(338,66): error CS0234: The type or namespace name 'ReplaceParameters' does not exist in the namespace 'Frends.Regex' (are you missing an assembly reference?)

Frends.ExecutableProcess.frends_UTIL_Trans.cs(342,107): error CS0234: The type or namespace name 'ReplaceParameters' does not exist in the namespace 'Frends.Regex' (are you missing an assembly reference?)

Frends.ExecutableProcess.frends_UTIL_Trans.cs(376,66): error CS0234: The type or namespace name 'ReplaceParameters' does not exist in the namespace 'Frends.Regex' (are you missing an assembly reference?)

Frends.ExecutableProcess.frends_UTIL_Trans.cs(380,107): error CS0234: The type or namespace name 'ReplaceParameters' does not exist in the namespace 'Frends.Regex' (are you missing an assembly reference?)

Frends.ExecutableProcess.frends_UTIL_Trans.cs(414,66): error CS0234: The type or namespace name 'ReplaceParameters' does not exist in the namespace 'Frends.Regex' (are you missing an assembly reference?)

Frends.ExecutableProcess.frends_UTIL_Trans.cs(418,107): error CS0234: The type or namespace name 'ReplaceParameters' does not exist in the namespace 'Frends.Regex' (are you missing an assembly reference?)

Frends.ExecutableProcess.frends_UTIL_Trans.cs(452,66): error CS0234: The type or namespace name 'ReplaceParameters' does not exist in the namespace 'Frends.Regex' (are you missing an assembly reference?)

Frends.ExecutableProcess.frends_UTIL_Trans.cs(456,107): error CS0234: The type or namespace name 'ReplaceParameters' does not exist in the namespace 'Frends.Regex' (are you missing an assembly reference?) 

TraceId: 00-24c2ce55b8c5402897f64f16b245adfe-bef1785710fd4009-01"

There might be a compatibility issue with net 8.0 with this task. This should be investigated and fixed.

**Comment by jefim** [comment]
Creating a new process in Frends with .NET 8 does not produce any error, so this might be an internal Frends migration error. There is nothing to fix on the task side as the error cannot be reproduced and/or fixed in task code.
