### ISSUE TITLE
Regex.Replace bug with Frends 5.7. 

### ISSUE THREAD

**Issue by RikuVirtanen** [FrendsPlatform/Frends.Regex#25]
Task is targeting .Net6 and it seems that .Net8 targeted processes can’t compile with the Task. The namespace is not even used inside the Task that is stated in the error message 'ReplaceResult':

![Untitled](https://github.com/user-attachments/assets/be10dae9-2b56-4f67-8549-8cd57a547618)

**Comment by jefim** [comment]
Fixed by #26
