### ISSUE TITLE
Frends.Regex.IsMatch initial implementation

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.Regex#3]
Create initial implementation for IsMatch task, using the simple tasks IsMatch task as baseline.

In addition:

- The task should have its own nuget (as opposed to having a generic zip package)
- The task has to have good unit test coverage, as zipping is something that can be automated
- No integration tests required besides just testing zipping in unit tests
- It would be nice to have some performance indication in the performance test section of the readme.

**Comment by hiqdani** [comment]
Initial implementation done.
- Task does IsMatch as expected
- Test coverage is adequate
- Task gets packed in a separate nuget with `dotnet pack --configuration Release`
